### ISSUE TITLE
mpc -v didn't work for me

### ISSUE THREAD

**Issue by GarthTheChicken** [CharlesSchimmel/nowPlaying#2]
Ubuntu 15.10
mpd 0.19.0
mpc 0.27-1

I had to change this to mpc version in the install script as the script kept complaining about mpc not being installed. mpc -v returns the current song, state and gain info which I would've thought would satisfy the check but it didn't.

I also had to set an environmental as I have mpd set to a non-default port due to it clashing but that's my issue not yours :)

Overall the script seems to work well and sees my album art so well done.

**Comment by CharlesSchimmel** [comment]
Thanks! I've changed the install script accordingly.
